### ISSUE TITLE
[BUG] Count leading zeros can't be used at compile time

### ISSUE THREAD

**Issue by martinvuyk** [modular/max#3847]
### Bug description
Count leading zeros can't be used at compile time. This is actually part of #933. This blocks a lot of other work to fully support unicode due to it needing this function.

part of the error: `note: LLVM intrinsic operand has unknown value: #pop<simd 15> : !pop.scalar<ui8>`

CC: @lattner 

### Steps to reproduce

```mojo
from bit import count_leading_zeros

fn _utf8_first_byte_sequence_length(b: Byte) -> Int:
    """Get the length of the sequence starting with given byte. Do note that
    this does not work correctly if given a continuation byte."""

    debug_assert(
        (b & 0b1100_0000) != 0b1000_0000,
        "Function does not work correctly if given a continuation byte.",
    )
    return int(count_leading_zeros(~b)) + int(b < 0b1000_0000)

fn main():
    print(_utf8_first_byte_sequence_length(ord("a")) == 1)
    print(_utf8_first_byte_sequence_length("🔥".as_bytes()[0]) == 4)
    alias `🔥` = "🔥".as_bytes()[0]
    alias length = _utf8_first_byte_sequence_length(`🔥`)
    print(length == 4)
```

### System information

```shell
- Provide version information for Mojo by pasting the output of `mojo -v`
`mojo 24.6.0.dev2024120805`
```

**Comment by martinvuyk** [comment]
Why would this not be planned? we need Unicode support in `StringLiteral`. And the `StringSlice` iterator uses this function, and many other things that users will want to run at compile time.

Unless we get a way to branch when the code is running at compile time, this is needed

**Comment by lattner** [comment]
I don't know why it was closed, but I think should work now.

**Comment by soraros** [comment]
@lattner It only works for `Int`. The following still crashes.

```mojo
from bit import count_leading_zeros

fn main():
  alias res = count_leading_zeros(Int32(0b1111_1111))  # note: failed to interpret function @stdlib::bit::bit::count_leading_zeros[::DType,::Int](::SIMD[$0, $1]),type=si32,width=1
  print(res)
```

**Comment by lattner** [comment]
Aha, thank you!  We weren't handling llvm intrinsics that returned SIMD with integer elements.  Fixed in main
